name: Build pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pages: write

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install oranda
        shell: bash
        run: "curl --proto '=https' --tlsv1.2 -LsSf https://axodotdev.artifacts.axodotdev.host/oranda/v0.6.5/oranda-installer.sh | sh"

      - name: Build site
        run: |
          source $HOME/.cargo/env
          oranda build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: "ubuntu-22.04"

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
